// Generated by gencpp from file progetto/Rest.msg
// DO NOT EDIT!


#ifndef PROGETTO_MESSAGE_REST_H
#define PROGETTO_MESSAGE_REST_H

#include <ros/service_traits.h>


#include <progetto/RestRequest.h>
#include <progetto/RestResponse.h>


namespace progetto
{

struct Rest
{

typedef RestRequest Request;
typedef RestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Rest
} // namespace progetto


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::progetto::Rest > {
  static const char* value()
  {
    return "b6a73f722475d64a28238118997ef482";
  }

  static const char* value(const ::progetto::Rest&) { return value(); }
};

template<>
struct DataType< ::progetto::Rest > {
  static const char* value()
  {
    return "progetto/Rest";
  }

  static const char* value(const ::progetto::Rest&) { return value(); }
};


// service_traits::MD5Sum< ::progetto::RestRequest> should match
// service_traits::MD5Sum< ::progetto::Rest >
template<>
struct MD5Sum< ::progetto::RestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::progetto::Rest >::value();
  }
  static const char* value(const ::progetto::RestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::progetto::RestRequest> should match
// service_traits::DataType< ::progetto::Rest >
template<>
struct DataType< ::progetto::RestRequest>
{
  static const char* value()
  {
    return DataType< ::progetto::Rest >::value();
  }
  static const char* value(const ::progetto::RestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::progetto::RestResponse> should match
// service_traits::MD5Sum< ::progetto::Rest >
template<>
struct MD5Sum< ::progetto::RestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::progetto::Rest >::value();
  }
  static const char* value(const ::progetto::RestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::progetto::RestResponse> should match
// service_traits::DataType< ::progetto::Rest >
template<>
struct DataType< ::progetto::RestResponse>
{
  static const char* value()
  {
    return DataType< ::progetto::Rest >::value();
  }
  static const char* value(const ::progetto::RestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROGETTO_MESSAGE_REST_H
