// Generated by gencpp from file progetto/StartAwareness.msg
// DO NOT EDIT!


#ifndef PROGETTO_MESSAGE_STARTAWARENESS_H
#define PROGETTO_MESSAGE_STARTAWARENESS_H

#include <ros/service_traits.h>


#include <progetto/StartAwarenessRequest.h>
#include <progetto/StartAwarenessResponse.h>


namespace progetto
{

struct StartAwareness
{

typedef StartAwarenessRequest Request;
typedef StartAwarenessResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartAwareness
} // namespace progetto


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::progetto::StartAwareness > {
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::progetto::StartAwareness&) { return value(); }
};

template<>
struct DataType< ::progetto::StartAwareness > {
  static const char* value()
  {
    return "progetto/StartAwareness";
  }

  static const char* value(const ::progetto::StartAwareness&) { return value(); }
};


// service_traits::MD5Sum< ::progetto::StartAwarenessRequest> should match
// service_traits::MD5Sum< ::progetto::StartAwareness >
template<>
struct MD5Sum< ::progetto::StartAwarenessRequest>
{
  static const char* value()
  {
    return MD5Sum< ::progetto::StartAwareness >::value();
  }
  static const char* value(const ::progetto::StartAwarenessRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::progetto::StartAwarenessRequest> should match
// service_traits::DataType< ::progetto::StartAwareness >
template<>
struct DataType< ::progetto::StartAwarenessRequest>
{
  static const char* value()
  {
    return DataType< ::progetto::StartAwareness >::value();
  }
  static const char* value(const ::progetto::StartAwarenessRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::progetto::StartAwarenessResponse> should match
// service_traits::MD5Sum< ::progetto::StartAwareness >
template<>
struct MD5Sum< ::progetto::StartAwarenessResponse>
{
  static const char* value()
  {
    return MD5Sum< ::progetto::StartAwareness >::value();
  }
  static const char* value(const ::progetto::StartAwarenessResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::progetto::StartAwarenessResponse> should match
// service_traits::DataType< ::progetto::StartAwareness >
template<>
struct DataType< ::progetto::StartAwarenessResponse>
{
  static const char* value()
  {
    return DataType< ::progetto::StartAwareness >::value();
  }
  static const char* value(const ::progetto::StartAwarenessResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROGETTO_MESSAGE_STARTAWARENESS_H
