// Generated by gencpp from file progetto/StopAwarenessResponse.msg
// DO NOT EDIT!


#ifndef PROGETTO_MESSAGE_STOPAWARENESSRESPONSE_H
#define PROGETTO_MESSAGE_STOPAWARENESSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace progetto
{
template <class ContainerAllocator>
struct StopAwarenessResponse_
{
  typedef StopAwarenessResponse_<ContainerAllocator> Type;

  StopAwarenessResponse_()
    : response()  {
    }
  StopAwarenessResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::progetto::StopAwarenessResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::progetto::StopAwarenessResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StopAwarenessResponse_

typedef ::progetto::StopAwarenessResponse_<std::allocator<void> > StopAwarenessResponse;

typedef boost::shared_ptr< ::progetto::StopAwarenessResponse > StopAwarenessResponsePtr;
typedef boost::shared_ptr< ::progetto::StopAwarenessResponse const> StopAwarenessResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::progetto::StopAwarenessResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::progetto::StopAwarenessResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::progetto::StopAwarenessResponse_<ContainerAllocator1> & lhs, const ::progetto::StopAwarenessResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::progetto::StopAwarenessResponse_<ContainerAllocator1> & lhs, const ::progetto::StopAwarenessResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace progetto

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::progetto::StopAwarenessResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::progetto::StopAwarenessResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::progetto::StopAwarenessResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::progetto::StopAwarenessResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::progetto::StopAwarenessResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::progetto::StopAwarenessResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::progetto::StopAwarenessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::progetto::StopAwarenessResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::progetto::StopAwarenessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "progetto/StopAwarenessResponse";
  }

  static const char* value(const ::progetto::StopAwarenessResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::progetto::StopAwarenessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
;
  }

  static const char* value(const ::progetto::StopAwarenessResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::progetto::StopAwarenessResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopAwarenessResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::progetto::StopAwarenessResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::progetto::StopAwarenessResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROGETTO_MESSAGE_STOPAWARENESSRESPONSE_H
