// Generated by gencpp from file progetto/StopAwareness.msg
// DO NOT EDIT!


#ifndef PROGETTO_MESSAGE_STOPAWARENESS_H
#define PROGETTO_MESSAGE_STOPAWARENESS_H

#include <ros/service_traits.h>


#include <progetto/StopAwarenessRequest.h>
#include <progetto/StopAwarenessResponse.h>


namespace progetto
{

struct StopAwareness
{

typedef StopAwarenessRequest Request;
typedef StopAwarenessResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopAwareness
} // namespace progetto


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::progetto::StopAwareness > {
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::progetto::StopAwareness&) { return value(); }
};

template<>
struct DataType< ::progetto::StopAwareness > {
  static const char* value()
  {
    return "progetto/StopAwareness";
  }

  static const char* value(const ::progetto::StopAwareness&) { return value(); }
};


// service_traits::MD5Sum< ::progetto::StopAwarenessRequest> should match
// service_traits::MD5Sum< ::progetto::StopAwareness >
template<>
struct MD5Sum< ::progetto::StopAwarenessRequest>
{
  static const char* value()
  {
    return MD5Sum< ::progetto::StopAwareness >::value();
  }
  static const char* value(const ::progetto::StopAwarenessRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::progetto::StopAwarenessRequest> should match
// service_traits::DataType< ::progetto::StopAwareness >
template<>
struct DataType< ::progetto::StopAwarenessRequest>
{
  static const char* value()
  {
    return DataType< ::progetto::StopAwareness >::value();
  }
  static const char* value(const ::progetto::StopAwarenessRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::progetto::StopAwarenessResponse> should match
// service_traits::MD5Sum< ::progetto::StopAwareness >
template<>
struct MD5Sum< ::progetto::StopAwarenessResponse>
{
  static const char* value()
  {
    return MD5Sum< ::progetto::StopAwareness >::value();
  }
  static const char* value(const ::progetto::StopAwarenessResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::progetto::StopAwarenessResponse> should match
// service_traits::DataType< ::progetto::StopAwareness >
template<>
struct DataType< ::progetto::StopAwarenessResponse>
{
  static const char* value()
  {
    return DataType< ::progetto::StopAwareness >::value();
  }
  static const char* value(const ::progetto::StopAwarenessResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROGETTO_MESSAGE_STOPAWARENESS_H
