// Generated by gencpp from file progetto/StopAwarenessRequest.msg
// DO NOT EDIT!


#ifndef PROGETTO_MESSAGE_STOPAWARENESSREQUEST_H
#define PROGETTO_MESSAGE_STOPAWARENESSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace progetto
{
template <class ContainerAllocator>
struct StopAwarenessRequest_
{
  typedef StopAwarenessRequest_<ContainerAllocator> Type;

  StopAwarenessRequest_()
    {
    }
  StopAwarenessRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::progetto::StopAwarenessRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::progetto::StopAwarenessRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopAwarenessRequest_

typedef ::progetto::StopAwarenessRequest_<std::allocator<void> > StopAwarenessRequest;

typedef boost::shared_ptr< ::progetto::StopAwarenessRequest > StopAwarenessRequestPtr;
typedef boost::shared_ptr< ::progetto::StopAwarenessRequest const> StopAwarenessRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::progetto::StopAwarenessRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::progetto::StopAwarenessRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace progetto

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::progetto::StopAwarenessRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::progetto::StopAwarenessRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::progetto::StopAwarenessRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::progetto::StopAwarenessRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::progetto::StopAwarenessRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::progetto::StopAwarenessRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::progetto::StopAwarenessRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::progetto::StopAwarenessRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::progetto::StopAwarenessRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "progetto/StopAwarenessRequest";
  }

  static const char* value(const ::progetto::StopAwarenessRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::progetto::StopAwarenessRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::progetto::StopAwarenessRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::progetto::StopAwarenessRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopAwarenessRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::progetto::StopAwarenessRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::progetto::StopAwarenessRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PROGETTO_MESSAGE_STOPAWARENESSREQUEST_H
