// Generated by gencpp from file progetto/VoiceDetectionService.msg
// DO NOT EDIT!


#ifndef PROGETTO_MESSAGE_VOICEDETECTIONSERVICE_H
#define PROGETTO_MESSAGE_VOICEDETECTIONSERVICE_H

#include <ros/service_traits.h>


#include <progetto/VoiceDetectionServiceRequest.h>
#include <progetto/VoiceDetectionServiceResponse.h>


namespace progetto
{

struct VoiceDetectionService
{

typedef VoiceDetectionServiceRequest Request;
typedef VoiceDetectionServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VoiceDetectionService
} // namespace progetto


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::progetto::VoiceDetectionService > {
  static const char* value()
  {
    return "c4e176c9f8ad32507aa931a67656b59c";
  }

  static const char* value(const ::progetto::VoiceDetectionService&) { return value(); }
};

template<>
struct DataType< ::progetto::VoiceDetectionService > {
  static const char* value()
  {
    return "progetto/VoiceDetectionService";
  }

  static const char* value(const ::progetto::VoiceDetectionService&) { return value(); }
};


// service_traits::MD5Sum< ::progetto::VoiceDetectionServiceRequest> should match
// service_traits::MD5Sum< ::progetto::VoiceDetectionService >
template<>
struct MD5Sum< ::progetto::VoiceDetectionServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::progetto::VoiceDetectionService >::value();
  }
  static const char* value(const ::progetto::VoiceDetectionServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::progetto::VoiceDetectionServiceRequest> should match
// service_traits::DataType< ::progetto::VoiceDetectionService >
template<>
struct DataType< ::progetto::VoiceDetectionServiceRequest>
{
  static const char* value()
  {
    return DataType< ::progetto::VoiceDetectionService >::value();
  }
  static const char* value(const ::progetto::VoiceDetectionServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::progetto::VoiceDetectionServiceResponse> should match
// service_traits::MD5Sum< ::progetto::VoiceDetectionService >
template<>
struct MD5Sum< ::progetto::VoiceDetectionServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::progetto::VoiceDetectionService >::value();
  }
  static const char* value(const ::progetto::VoiceDetectionServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::progetto::VoiceDetectionServiceResponse> should match
// service_traits::DataType< ::progetto::VoiceDetectionService >
template<>
struct DataType< ::progetto::VoiceDetectionServiceResponse>
{
  static const char* value()
  {
    return DataType< ::progetto::VoiceDetectionService >::value();
  }
  static const char* value(const ::progetto::VoiceDetectionServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROGETTO_MESSAGE_VOICEDETECTIONSERVICE_H
