// Generated by gencpp from file progetto/WakeUp.msg
// DO NOT EDIT!


#ifndef PROGETTO_MESSAGE_WAKEUP_H
#define PROGETTO_MESSAGE_WAKEUP_H

#include <ros/service_traits.h>


#include <progetto/WakeUpRequest.h>
#include <progetto/WakeUpResponse.h>


namespace progetto
{

struct WakeUp
{

typedef WakeUpRequest Request;
typedef WakeUpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WakeUp
} // namespace progetto


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::progetto::WakeUp > {
  static const char* value()
  {
    return "b6a73f722475d64a28238118997ef482";
  }

  static const char* value(const ::progetto::WakeUp&) { return value(); }
};

template<>
struct DataType< ::progetto::WakeUp > {
  static const char* value()
  {
    return "progetto/WakeUp";
  }

  static const char* value(const ::progetto::WakeUp&) { return value(); }
};


// service_traits::MD5Sum< ::progetto::WakeUpRequest> should match
// service_traits::MD5Sum< ::progetto::WakeUp >
template<>
struct MD5Sum< ::progetto::WakeUpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::progetto::WakeUp >::value();
  }
  static const char* value(const ::progetto::WakeUpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::progetto::WakeUpRequest> should match
// service_traits::DataType< ::progetto::WakeUp >
template<>
struct DataType< ::progetto::WakeUpRequest>
{
  static const char* value()
  {
    return DataType< ::progetto::WakeUp >::value();
  }
  static const char* value(const ::progetto::WakeUpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::progetto::WakeUpResponse> should match
// service_traits::MD5Sum< ::progetto::WakeUp >
template<>
struct MD5Sum< ::progetto::WakeUpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::progetto::WakeUp >::value();
  }
  static const char* value(const ::progetto::WakeUpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::progetto::WakeUpResponse> should match
// service_traits::DataType< ::progetto::WakeUp >
template<>
struct DataType< ::progetto::WakeUpResponse>
{
  static const char* value()
  {
    return DataType< ::progetto::WakeUp >::value();
  }
  static const char* value(const ::progetto::WakeUpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROGETTO_MESSAGE_WAKEUP_H
