// Generated by gencpp from file progetto/WakeUpResponse.msg
// DO NOT EDIT!


#ifndef PROGETTO_MESSAGE_WAKEUPRESPONSE_H
#define PROGETTO_MESSAGE_WAKEUPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace progetto
{
template <class ContainerAllocator>
struct WakeUpResponse_
{
  typedef WakeUpResponse_<ContainerAllocator> Type;

  WakeUpResponse_()
    : ack()  {
    }
  WakeUpResponse_(const ContainerAllocator& _alloc)
    : ack(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ack_type;
  _ack_type ack;





  typedef boost::shared_ptr< ::progetto::WakeUpResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::progetto::WakeUpResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WakeUpResponse_

typedef ::progetto::WakeUpResponse_<std::allocator<void> > WakeUpResponse;

typedef boost::shared_ptr< ::progetto::WakeUpResponse > WakeUpResponsePtr;
typedef boost::shared_ptr< ::progetto::WakeUpResponse const> WakeUpResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::progetto::WakeUpResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::progetto::WakeUpResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::progetto::WakeUpResponse_<ContainerAllocator1> & lhs, const ::progetto::WakeUpResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ack == rhs.ack;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::progetto::WakeUpResponse_<ContainerAllocator1> & lhs, const ::progetto::WakeUpResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace progetto

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::progetto::WakeUpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::progetto::WakeUpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::progetto::WakeUpResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::progetto::WakeUpResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::progetto::WakeUpResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::progetto::WakeUpResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::progetto::WakeUpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6a73f722475d64a28238118997ef482";
  }

  static const char* value(const ::progetto::WakeUpResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6a73f722475d64aULL;
  static const uint64_t static_value2 = 0x28238118997ef482ULL;
};

template<class ContainerAllocator>
struct DataType< ::progetto::WakeUpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "progetto/WakeUpResponse";
  }

  static const char* value(const ::progetto::WakeUpResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::progetto::WakeUpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ack\n"
;
  }

  static const char* value(const ::progetto::WakeUpResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::progetto::WakeUpResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WakeUpResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::progetto::WakeUpResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::progetto::WakeUpResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROGETTO_MESSAGE_WAKEUPRESPONSE_H
